GET http://localhost:3000/dev/say/teste
Content-Type: application/json

###
GET http://localhost:3000/dev/
Content-Type: application/json
###
GET http://localhost:3000/dev/getCustomer/oi
Content-Type: application/json