service: serverless-example

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-1
  versionFunctions: true
  deploymentBucket:
    name: serverless-dev

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'